services:
  db:
    image: postgres
    restart: always
    env_file:
      - "./apps/server/.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
volumes:
  postgres_data:
